import { IMAGES } from './images'
import type { Job, Course, QuizQuestion } from '@/types'

export const SEED_JOBS: Job[] = [
  {
    id: '1',
    title: 'Network Engineer',
    company: 'MTN Eswatini',
    company_logo: IMAGES.mtn,
    location: 'Mbabane, Hhohho',
    type: 'FULL-TIME',
    category: 'Technology',
    salary: 'E12,000/mo',
    experience_level: '3+ years',
    description:
      'We are looking for a skilled Network Engineer to join our growing team at MTN Eswatini. You will be responsible for designing, implementing, and maintaining our network infrastructure to support the kingdom\'s largest telecoms provider.',
    requirements: [
      "Bachelor's degree in IT or related field",
      'CCNA or equivalent certification',
      '3+ years network engineering experience',
      'Cisco & Juniper expertise',
      'Strong troubleshooting skills',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Graduate Intern – IT',
    company: 'Standard Bank Eswatini',
    company_logo: IMAGES.standardBank,
    location: 'Manzini, Hub',
    type: 'INTERNSHIP',
    category: 'Finance',
    salary: 'E3,500/mo',
    experience_level: 'Graduate',
    description:
      'Join Standard Bank Eswatini\'s IT team as a graduate intern. Gain hands-on experience in banking technology, fintech solutions, and digital transformation initiatives.',
    requirements: [
      'BSc Computer Science or IT',
      '0–1 year experience',
      'Analytical and problem-solving skills',
      'Team player with good communication',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'Eswatini Bank',
    company_logo: IMAGES.eswatiniBank,
    location: 'Mbabane (Remote)',
    type: 'REMOTE',
    category: 'Technology',
    salary: 'E9,000/mo',
    experience_level: '2+ years',
    description:
      'Design beautiful, user-centred digital banking experiences for Eswatini Bank\'s growing digital customer base. Work closely with product and engineering teams.',
    requirements: [
      'Portfolio required',
      'Figma proficiency',
      'UX research skills',
      '2+ years design experience',
      'Mobile-first design knowledge',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Data Analyst Intern',
    company: 'UNICEF Eswatini',
    company_logo: IMAGES.unicef,
    location: 'Mbabane',
    type: 'INTERNSHIP',
    category: 'Technology',
    salary: 'E4,000/mo',
    experience_level: 'Graduate',
    description:
      "Support UNICEF Eswatini's data analysis for child welfare programmes across the kingdom. Help visualise insights that drive impact for Eswatini's most vulnerable children.",
    requirements: [
      'Statistics or Data Science degree',
      'Python / R proficiency',
      'Advanced Excel',
      'Data visualisation skills',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Civil Engineer',
    company: 'Eswatini Water Services',
    company_logo: IMAGES.waterServices,
    location: 'Ezulwini',
    type: 'FULL-TIME',
    category: 'Engineering',
    salary: 'E15,000/mo',
    experience_level: '5+ years',
    description:
      'Lead infrastructure development projects for water supply and sanitation across Eswatini. You will oversee design, procurement, and site supervision for critical national infrastructure.',
    requirements: [
      'BSc Civil Engineering',
      'Professional Engineer registration',
      '5+ years experience',
      'Project management certification',
      'AutoCAD proficiency',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Marketing Manager',
    company: 'Nedbank Eswatini',
    company_logo: IMAGES.nedbank,
    location: 'Manzini',
    type: 'FULL-TIME',
    category: 'Business',
    salary: 'E14,000/mo',
    experience_level: '4+ years',
    description:
      "Drive brand awareness and customer acquisition strategies for Nedbank Eswatini's growing retail portfolio. Manage campaigns across digital, print, and events.",
    requirements: [
      'Marketing or Business degree',
      '4+ years marketing experience',
      'Digital marketing expertise',
      'Campaign management skills',
      'Budget management experience',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Software Developer',
    company: 'SwaziTech Solutions',
    company_logo: IMAGES.techCompany,
    location: 'Mbabane',
    type: 'FULL-TIME',
    category: 'Technology',
    salary: 'E11,000/mo',
    experience_level: '2+ years',
    description:
      'Build and maintain enterprise software solutions for clients across Southern Africa. Work in an agile team using modern web technologies.',
    requirements: [
      'BSc Computer Science or equivalent',
      'React / Node.js expertise',
      '2+ years professional experience',
      'Agile / Scrum methodology',
      'Git version control',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Accounting Officer',
    company: 'Deloitte Eswatini',
    company_logo: IMAGES.deloitte,
    location: 'Mbabane',
    type: 'FULL-TIME',
    category: 'Finance',
    salary: 'E13,000/mo',
    experience_level: '3+ years',
    description:
      'Provide accounting and financial advisory services to top corporate clients in Eswatini. Work across audit, tax, and advisory engagements.',
    requirements: [
      'BCom Accounting or Finance',
      '3+ years experience',
      'ACCA / CIMA advantage',
      'Excellent analytical skills',
      'Client-facing experience',
    ],
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const SEED_COURSES: Course[] = [
  {
    id: '1',
    title: 'Digital Marketing Specialist',
    description:
      'Master digital marketing strategies, SEO, social media management, and analytics tailored for the African market.',
    category: 'Business',
    level: 'Intermediate',
    duration_hours: 6,
    thumbnail_url: IMAGES.coworkHero,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Project Management Basics',
    description:
      'Learn core project management principles applied to the Eswatini corporate landscape. Covers PMBOK, Agile, and local business context.',
    category: 'Business',
    level: 'Beginner',
    duration_hours: 4,
    thumbnail_url: IMAGES.moduleVideo,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Web Development Fundamentals',
    description:
      'Build modern websites using HTML, CSS, and JavaScript. Includes practical projects and a final portfolio piece.',
    category: 'Technology',
    level: 'Beginner',
    duration_hours: 8,
    thumbnail_url: IMAGES.resourceVideo,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Financial Literacy for Youth',
    description:
      'Understand money management, savings, budgeting, and investment basics — designed for young Emaswati entering the workforce.',
    category: 'Finance',
    level: 'Beginner',
    duration_hours: 3,
    thumbnail_url: IMAGES.financeLogo,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Entrepreneurship in Eswatini',
    description:
      'Build and grow a business in Eswatini. Covers company registration, SIPA incentives, funding, and go-to-market strategy.',
    category: 'Business',
    level: 'Intermediate',
    duration_hours: 5,
    thumbnail_url: IMAGES.interviewPrepHero,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Cybersecurity Essentials',
    description:
      'Protect digital assets and understand cybersecurity threats facing African organisations. Covers network security, phishing, and incident response.',
    category: 'Technology',
    level: 'Intermediate',
    duration_hours: 5,
    thumbnail_url: IMAGES.coworkHero,
    is_published: true,
    created_at: new Date().toISOString(),
  },
]

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    quiz_id: 'quiz-pm',
    question: 'What is the primary goal of project scope management?',
    options: [
      'Reducing project costs',
      'Defining what is included and excluded in a project',
      'Managing team communication',
      'Tracking project timelines',
    ],
    correct_index: 1,
    order_index: 1,
  },
  {
    id: 'q2',
    quiz_id: 'quiz-pm',
    question: 'Which project management framework uses sprints?',
    options: ['Waterfall', 'PRINCE2', 'Agile / Scrum', 'Critical Path Method'],
    correct_index: 2,
    order_index: 2,
  },
  {
    id: 'q3',
    quiz_id: 'quiz-pm',
    question: 'A stakeholder in project management refers to:',
    options: [
      'Only the project team',
      'Anyone who funds the project',
      'Anyone affected by or who affects the project',
      'Only the project manager',
    ],
    correct_index: 2,
    order_index: 3,
  },
  {
    id: 'q4',
    quiz_id: 'quiz-pm',
    question: 'What does PMBOK stand for?',
    options: [
      'Project Management Body of Knowledge',
      'Program Management Best Outcomes Knowledge',
      'Project Methods Business Operations Kit',
      'Planning Management Baseline of Knowledge',
    ],
    correct_index: 0,
    order_index: 4,
  },
]

export const INTERVIEW_QUESTIONS = [
  { question: 'Tell me about yourself.', topic: 'General' },
  {
    question:
      '"How would you align our regional expansion goals with the specific economic needs of the Shiselweni region?"',
    topic: 'Local Governance & Strategy',
  },
  { question: 'What is your expected salary?', topic: 'Compensation' },
  { question: 'How do you handle workplace conflict?', topic: 'Soft Skills' },
  { question: 'Where do you see yourself in 5 years?', topic: 'Career Goals' },
  {
    question: 'Describe a time you led a team under pressure.',
    topic: 'Leadership',
  },
  {
    question: 'Why do you want to work for this company?',
    topic: 'Motivation',
  },
]

export const COURSE_PROGRESS: Record<string, number> = {
  '1': 75,
  '2': 0,
  '3': 100,
  '4': 40,
  '5': 0,
  '6': 0,
}
